---
# Web root paths + app name + home (for ubuntu)
web_root_path_ubuntu: /var/www/app-test
web_server_group_ubuntu: www-data

app_name: python-sample-app
app_root_path: "{{ web_root_path }}/{{ app_name }}_webapp"

# NGINX
app_nginx_hostname: localhost
app_nginx_static_path: "{{ app_root_path }}/{{ app_name }}/static/"

# UWSGI
app_uwsgi_port: 5000
app_uwsgi_executable: "app:make_wsgi_app()"
app_uwsgi_envs: {}

# Virtualenvs
virtualenv_root_path: "{{ web_root_path }}/virtualenvs"
app_venv: "{{ virtualenv_root_path }}/{{ app_name }}"
