- name: distr
  debug:
    msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"
  #tags: agent_test
  
- name: Prepare
  block:
    - name: Prepare
      apt: 
        name: ["wget", "curl", "acl"]
        update_cache: true
        state: latest
  
      # Web root paths + app name + home
    - name: setup vars for ubuntu
      set_fact:
       web_root_path: "{{ web_root_path_ubuntu }}"
       web_server_group: "{{ web_server_group_ubuntu }}"

  when:
    ( (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20" ) )

#- include: postgres.yml
- include: web_data_folders.yml
- include: python.yml
- include: supervisor.yml
#- include: project.yml
- include: project.yml
#- include: nginx.yml
#- include: uwsgi.yml
