---
# tasks file for app-test

- name: distr
  debug:
    msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"
  #tags: agent_test

  
# Postgres install

- name: Install Postgres on Ubuntu
  block:
    - name: Prepare
      apt: 
        name: ["wget", "curl", "acl"]
        update_cache: true
        state: latest

    - name: Add pubkey Postgres repo
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
      
    - name: Add Postgres repo
      shell: "add-apt-repository \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main\""

    - name: Add Postgres key
      shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

    - name: Install Postgres
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - postgresql-11
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
        - python3-pip
        - virtualenv
    
#    - name: Prepare
#      apt: 
#        name: postgresql-11
#        state: latest

    - name: Check status Postgres
      shell: "systemctl status postgresql"

  when:
    ( (ansible_facts['distribution'] == "Ubuntu1" and ansible_facts['distribution_major_version'] == "20" ) )

- name: Install Postgres on CentOS
  block:
    - name: empty task
      debug:
        msg: "Empty"
  when:
    ( (ansible_facts['distribution'] == "CentOS" ) )
    
- name: Create Postgres db
  become_user: postgres
  postgresql_db:
    name: app
    state: present

- name: Create Postgres DB user
  become_user: postgres
  postgresql_user: 
    db: app
    name: worker
    password: worker
    priv: ALL
    state: present

- name: copy app
  become_user: deployer
  copy:
    src: "{{ project_name }}"
    dest: "/opt/"
    force: no
#  tags: copy

- name: create virtualenv 
  pip: "name=app-test virtualenv=/opt/{{project_name}}/env virtualenv_command=virtualenv"
  

#- name: Install project requirements
#  pip:
#    state: latest
#    requirements: "/opt/python-sample-app/requirements.txt"
#    virtualenv: "{{ venv_path }}"
#    virtualenv_python: python3.6
#    virtualenv_command: /usr/local/bin/virtualenv

##################################################################################
- name: Install python-dev
  apt: "name='python-dev' state=present force=yes"

- name: Install python-pip
  apt: "name='python-pip' state=present force=yes"

- name: install uwsgi
  pip: name=uwsgi

- name: Install supervisor

  apt: name=supervisor state=present force=yes
  when: is_installed.rc != 0

- name: Create UWSGI vassals directory
  file: "path={{vassals_dir}}  state=directory"

- name: setup uwsgi in supervisor
  template: "src=uwsgi-server.j2 dest={{supervisor_conf_dir}}/uwsgi-runner.conf"

- name: update supervisor
  supervisorctl: name=uwsgi-runner state=restarted

- name: setup project uwsgi configuration file
  template: "src=uwsgi.j2 dest=/home/{{project_name}}/{{project_name}}_uwsgi.ini"

- name: create a symlink of uwsgi in vassals
  file: "src=/home/{{project_name}}/{{project_name}}_uwsgi.ini dest=/etc/uwsgi/vassals/{{project_name}}_uwsgi.ini state=link"

- name: touch the symlink file
  command: "touch /etc/uwsgi/vassals/{{project_name}}_uwsgi.ini"
