---
- name: Install NGINX on Ubuntu
  block:

    - name: install nginx webserver
      apt: pkg=nginx-full state=present
      become: yes

    - name: configure nginx
      template: src=nginx.conf dest=/etc/nginx/sites-available/{{ nginx_app_config }}
      become: yes

    - name: link to enable nginx configuration
      file: state=link
            src=/etc/nginx/sites-available/{{ nginx_app_config }}
            path=/etc/nginx/sites-enabled/{{ nginx_app_config }}
      become: yes

    - name: disable default configuration
      file: state=absent path=/etc/nginx/sites-enabled/default
      become: yes
      notify: restart nginx

    - name: create webroot dir
      file: path={{ web_root_path }} state=directory
            group={{ web_server_group }} mode=0755
      become: yes

    - name: set nginx directories permissions
      file: path={{ item }} state=directory
            group={{ web_server_group }} mode=0755
      with_items:
        - /var/log/nginx
        - /etc/nginx
        - /etc/nginx/sites-available
        - /etc/nginx/sites-enabled
        - "{{ web_root_path }}"
      become: yes

    - name: set nginx logs permissions
      file: path=/var/log/nginx/{{ item }} state=file
            owner={{ web_server_group }} group={{ web_server_group }} mode=0644
      with_items:
        - access.log
        - error.log
  when:
    ( (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20" ) )
