---
- name: install python dev
  become: yes
  apt: 
    pkg: ['python-dev', 'python-setuptools', 'python3-pip'] 
    state: present

#- name: install pip
#  become: yes
#  easy_install: name=pip

#- name: install virtualenv
#  become: yes
#  pip: name={{ item }} state=present extra_args='--upgrade'
#  with_items:
#    - pip
#    - virtualenv
    
- name: Initiate virtualenv
  pip: virtualenv="{{ app_venv }}" 
       requirements="{{ app_root_path }}/requirements.txt"
