---
- name: install build utilities
  apt: pkg=build-essential state=present
  become: yes

- name: install python-dev package
  apt: pkg=python-dev state=present
  become: yes

- name: install uwsgi server
  pip: name=uwsgi virtualenv={{ uwsgi_venv }} version=2.0.15
  become: yes

- name: configure app on uwsgi server
  template: src=uwsgi.ini dest={{ uwsgi_config_path }}/{{ uwsgi_app_ini }}
  become: yes 

- name: Run migrations
  command: "{{ app_venv }}/bin/{{ app_migration_command }}"
  args:
    chdir: "{{ app_root_path }}"
  environment:
    FLASK_APP: app.py
    POSTGRESQL_URL: postgresql://worker:worker@localhost/app
    LANG: en_US.utf-8
  become: yes
  become_user: "{{ web_server_group }}"
  run_once: true
  #when: app_run_migrations


