---
# vars file for app-test
project_name: "python-sample-app"

# vars file for ansible-nginx-uwsgi-supervisor

# User
web_user: "{{ ansible_env.SUDO_USER }}"

# NGINX
nginx_app_config: "{{ app_name }}_uwsgi_nginx.conf"

# Supervisor
supervisor_app_config: "{{ app_name }}_supervisor.conf"

# UWSGI
uwsgi_venv: "{{ virtualenv_root_path }}/uwsgi"
uwsgi_config_path: "{{ web_root_path }}/config/uwsgi"
uwsgi_app_ini: "{{ app_name }}_uwsgi.ini"
uwsgi_app_service_name: "{{ app_name }}_uwsgi"

